// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVdIKAceCi8jtBYIWZtr-PVpHJjZYN_2U',
    appId: '1:23094452380:android:02986c1b5299155fb64d59',
    messagingSenderId: '23094452380',
    projectId: 'all-firebase-fc389',
    storageBucket: 'all-firebase-fc389.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTrD9oaHkV5XJs-vmOv1O5qpaoelhkahY',
    appId: '1:23094452380:ios:b31c489412d1a4bfb64d59',
    messagingSenderId: '23094452380',
    projectId: 'all-firebase-fc389',
    storageBucket: 'all-firebase-fc389.appspot.com',
    iosBundleId: 'com.example.machineTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTrD9oaHkV5XJs-vmOv1O5qpaoelhkahY',
    appId: '1:23094452380:ios:6573607f1f7e87bdb64d59',
    messagingSenderId: '23094452380',
    projectId: 'all-firebase-fc389',
    storageBucket: 'all-firebase-fc389.appspot.com',
    iosBundleId: 'com.example.machineTest.RunnerTests',
  );
}
